version: "3"

services:
  race-control-service:
    build: ./services/race-control-service
    ports:
      - "8091:8080"
      - "5006:5005"
    environment:
      - JAVA_TOOL_OPTIONS=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005

  drivers-mongodb:
    image: bitnami/mongodb:4.4.13
    ports:
      - "27017:27017"
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - MONGODB_ROOT_USER=root
      - MONGODB_ROOT_PASSWORD=root
      - MONGODB_USERNAME=f1-app
      - MONGODB_PASSWORD=f1-app
      - MONGODB_DATABASE=f1-project

  drivers-service:
    build: ./services/drivers-service
    ports:
      - "8090:8080"
      - "5005:5005"
    links:
      - drivers-mongodb
    environment:
      - MONGODB_HOST=drivers-mongodb
      - JAVA_TOOL_OPTIONS=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005

  gateway-api:
    build: ./services/gateway-api
    ports:
      - "8089:8080"
      - "5004:5005"
    links:
      - drivers-service
      - race-control-service
    environment:
      - JAVA_TOOL_OPTIONS=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005
