info:
  app:
    name: "@project.name@"
    version: "@project.version@"

spring:
  application.name: "@project.name@"
  graphql.graphiql.enabled: true

drivers-service:
  baseUrl: http://drivers-service:8080
  get.uri: /drivers/