info:
  app:
    name: "@project.name@"
    version: "@project.version@"
spring:
  application.name: "@project.name@"

kafka:
  bootstrapAddress: ${KAFKA_BOOTSTRAP_ADDR:localhost\:9092}
  topics:
    race: f1-race
