info:
  app:
    name: "@project.name@"
    version: "@project.version@"
spring:
  application.name: "@project.name@"
  kafka:
    bootstrap-servers:
      - ${KAFKA_BOOTSTRAP_ADDR:kafka-1\:9092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.add.type.headers: false

kafka:
  enabled: false
  topics:
    race: f1-race


---
spring:
  config:
    activate:
      on-profile: prod

kafka.enabled: true
