info:
  app:
    name: "@project.name@"
    version: "@project.version@"

spring:
  application.name: "@project.name@"
  data:
    mongodb:
      host: ${MONGODB_HOST:localhost}
      port: 27017
      database: f1-project
      username: f1-app
      password: f1-app
  kafka:
    consumer:
      bootstrap-servers:
        - ${KAFKA_BOOTSTRAP_ADDR:localhost\:9092}
      group-id: drivers
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      auto-offset-reset: earliest
      properties:
        spring.json.trusted.packages: "*"
    listener:
      ack-mode: MANUAL_IMMEDIATE

kafka:
  topics:
    race: f1-race
  properties.type:
    race: "spring.json.value.default.type=io.dutra.f1.commons.model.aggregates.Race"
